import Head from "next/head";
import styles from "../styles/Home.module.scss";
import FeatureCards from "../components/featureCards";
import PopularCards from "../components/popularCards";
import Layout from "../components/Layout";
import RecentCards from "../components/recentCards";
import TopAuthorCards from "../components/topAuthorCards";
import HomeCategories from "../components/homeCategories";
import { getAuthors, getCategories, getPosts } from "../service";
// import Context from "../components/Context";

export default function Home({ posts, authors, categories }) {
  return (
    <>
      <Head>
        <title>Blog Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout categories={categories}>
        <div className={styles.hero}>
          <div className={styles.wrapper}>
            <FeatureCards posts={posts} />
            <PopularCards />
          </div>
        </div>

        <div className={styles.home_bottom_container}>
          <div className={styles.recent}>
            <RecentCards posts={posts} />
          </div>
          <div className={styles.home_bottom_right}>
            <TopAuthorCards authors={authors} />
            <HomeCategories categories={categories} />
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const posts = await getPosts();
  const authors = await getAuthors();
  const categories = await getCategories();

  return {
    props: { posts, authors, categories },
  };
}
