import Head from "next/head";
import styles from "../styles/Home.module.scss";
import FeatureCards from "../components/featureCards";
import PopularCards from "../components/popularCards";
import Layout from "../components/layout";
import RecentCards from "../components/recentCards";
import TopAuthorCards from "../components/topAuthorCards";
import HomeCategories from "../components/homeCategories";
import { getPosts } from "../service";
import Link from "next/link";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.hero}>
          <div className={styles.wrapper}>
            <FeatureCards posts={posts} />
            <PopularCards />
          </div>
        </div>

        <div className={styles.home_bottom_container}>
          <div className={styles.recent}>
            <RecentCards posts={posts} />
          </div>
          <div className={styles.home_bottom_right}>
            <TopAuthorCards />
            <HomeCategories />
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const posts = await getPosts();

  return {
    props: { posts },
  };
}
